### PR TITLE
use stack ncdiag, update hera.gnu hpc-stack, update to head of develop

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**
This PR updates 
- `gsi_common.lua` to use machine specific stack `ncdiag/1.1.1`
- `gsi_hera.gnu.lua` to use epic hpc-stack
- files `enkf/gridio_fv3reg.f90`, `enkf/gridio_gfs.f90`, `src/enkf/innovstats.f90` to current head (333ae16) of NOAA-EMC/GSI `develop`

**NOTE:**  The change to `gsi_common.lua` results in the WCOSS2 build failing because `ncdiag/1.1.1` has not yet been installed in the official WCOSS2 stack.

Addresses open items in PR [#571](https://github.com/NOAA-EMC/GSI/pull/571). 

**Type of change**
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
`intel2022` has been cloned and built on Orion and Hera.   Both intel and gnu builds were executed on Hera.  All builds successfully completed.

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA It looks like the `w3nco` load snuck it's way back into the `gsi_common.lua` modulefile.  This should be removed.

**Comment by RussTreadon-NOAA** [comment]
`load(pathJoin("w3nco", w3nco_ver))` is in [`hu5970:intel2022`](https://github.com/hu5970/GSI/tree/intel2022).   It entered `gsi_common.lua` at [`1359145`](https://github.com/hu5970/GSI/commit/13591455393b4d30027362f9176f4600edf1621d).

I will remove the `w3nco` entry from `gsi_common.lua` in `RussTreadon-NOAA:intel2022` ... though doing so is outside the intended scope of this PR.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA  and @natalie-perlin, `modulefiles/gsi_cheyenne.gnu.lua` references `w3nco` with the following comment
```
-- Preload w3nco to work around nemsio "find_dependency(w3nco)" hpc-stack bug
load("w3nco/2.4.1")
```

Has the hpc-stack bug on Cheyenne been resolved?  If so, I will remove this `w3nco` reference, too.

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA @natalie-perlin I verified that this is not an issue for `nemsio/2.5.4` on Cheyenne when loading through `hpc-gnu/10.1.0 hpc-mpt/2.25`.  I think this is only an issue for `nemsio/2.5.2`, which uses `w3nco`, while `2.5.4` does not.  If the plan is to use `mpt/2.22`, then I cannot say for certain as it does not exist yet, but I'm strongly inclined to say it would be fine to remove it.

**Comment by natalie-perlin** [comment]
@RussTreadon-NOAA @DavidHuber-NOAA -
Yes, the dependency is indeed only for nemsio/2.5.2. 
Also, use of mpt/2.22 was retired for use with hpc-stack. We have several gnu-based hpc-stacks in EPIC locations, all with mpt/2.25. Neither UFS-WM, nor UFS-SRW use the older 2.22 version since last year.

**Comment by RussTreadon-NOAA** [comment]
@hu5970 , if you are OK with these changes, would you please approve and merge.  I can not approve my own PR.

These changes in this PR are twofold:
- update modulefiles:  use `ncdiag/1.1.1` and use epic-stack for `gsi_hera.gnu.lua`
- update `hu5970:intel2022` to the head of `develop`

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA Can we also remove the w3nco load from gsi_common.lua?  This dependency was removed with nemsio/2.5.4.  @natalie-perlin confirmed that it is not needed for Cheyenne, either.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA , `w3nco` removed at [`3d47231`](https://github.com/hu5970/GSI/pull/12/commits/3d4723105b111855d4d252e701f3a376e787d30b).  Please confirm that this is satisfactory.

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA Yes, thank you, this is what was desired.

**Review by hu5970 — APPROVED** [review]

**Pull request merged**
