### PR TITLE
Update CI version of ncdiag, merge in develop

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
This updates the version of ncdiag to 1.1.0 in ci/spack.yaml, exits guess_grid.f90 if an allocation fails, and merges in the latest version of develop while fixing conflicts.  This should resolve all of Russ's comments except for Gaea.

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
@aerorahul @RussTreadon-NOAA Perhaps we can take up the ncdiag/spack conversation here.

**Comment by RussTreadon-NOAA** [comment]
I see the checksum error you mention in `install-dependencies-with-spack`
```
==> Installing gsi-ncdiag-1.1.0-2ebgnagbzgora523suak7ppsltv2ooqm
==> No binary for gsi-ncdiag-1.1.0-2ebgnagbzgora523suak7ppsltv2ooqm found: installing from source
==> Warning: There is no checksum on file to fetch gsi-ncdiag@1.1.0 safely.
==> Error: FetchError: Will not fetch gsi-ncdiag@1.1.0
```

I do not see what else to change in `ci/spack.yaml` to get past this error.

**Comment by DavidHuber-NOAA** [comment]
I see now that the new version needs to have its checksum added to the spack repo.  The alternative is to disable checksum checking, but I'd like to get @aerorahul's opinion on that.  I'm going to open a PR into spack to add it, but I'm not sure how long that will take.

**Comment by DavidHuber-NOAA** [comment]
@aerorahul @hu5970 Asking around, PRs into spack can sometimes take a long time, with over 800 currently waiting in queue to that repo.  Can we move ahead with this PR and address this CI failure when the spack PR is merged?  @RussTreadon-NOAA no offense in not asking you, I just don't want to void your reviewer status.

**Review by hu5970 — APPROVED** [review]

**Pull request merged**
